# Redirect all HTTP to HTTPS
server {
    listen 80;
    server_name school.mohibs.in api.school.mohibs.in;
    return 301 https://$host$request_uri;
}

# Client
server {
    listen 443 ssl;
    server_name school.mohibs.in;

    ssl_certificate /etc/letsencrypt/live/school.mohibs.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/school.mohibs.in/privkey.pem;

    location / {
        proxy_pass http://client:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# API
server {
    listen 443 ssl;
    server_name api.school.mohibs.in;

    ssl_certificate /etc/letsencrypt/live/school.mohibs.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/school.mohibs.in/privkey.pem;

    location / {
        proxy_pass http://server:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}